# Generated by Django 6.0.1 on 2026-01-20 22:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Settings', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('driver', 'Driver'), ('valet', 'Valet')], default='customer', max_length=20)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_created_at', models.DateTimeField(auto_now_add=True)),
                ('token_updated_at', models.DateTimeField(auto_now=True)),
                ('about_me', models.TextField(blank=True, help_text="User's bio or description about themselves", null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user first started using the platform')),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Account'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='card', max_length=20)),
                ('payment_frequency', models.CharField(choices=[('instant', 'Instant'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='instant', max_length=20)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile image stored in S3', null=True, upload_to='profile_images/')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, default='US', max_length=100, null=True)),
                ('address_latitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text="Latitude of the user's street address (reverse geocoded)", max_digits=9, null=True)),
                ('address_longitude', models.DecimalField(blank=True, db_index=True, decimal_places=6, help_text="Longitude of the user's street address (reverse geocoded)", max_digits=9, null=True)),
                ('current_latitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, help_text='Current latitude coordinate (real-time GPS location)', max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, help_text='Current longitude coordinate (real-time GPS location)', max_digits=10, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, help_text='Timestamp of last location update', null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(blank=True, db_index=True, decimal_places=1, help_text='User rating from 1.0 to 5.0 stars (1 decimal place)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_contact_id', models.ForeignKey(blank=True, help_text="ID of the user's emergency contact", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.emergencycontact')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('notification_id', models.ForeignKey(blank=True, help_text="ID of the user's notification settings", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.notification')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('work_preference_id', models.ForeignKey(blank=True, help_text="ID of the user's work preference settings", null=True, on_delete=django.db.models.deletion.SET_NULL, to='Settings.workpreference')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
